version: "3.7"
services:
    app:
        build:
            args:
                user: php
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: app-web
        container_name: container-name
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - app-network
    db:
        image: mysql:8.0
        container_name: db-container-name
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - app-network
    nginx:
        image: nginx:alpine
        container_name: nginx-container-name
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - app-network
networks:
  app-network:
      driver: bridge
